import os
import sys
import time
def help_menu():
    print('hi')
def start_game():
    game_structure()
def options():
  options_choice = input(">")
  if options_choice  == "play":
    start_game()
  elif options_choice== "help":
    help_menu()
  elif options_choice == "quit":
    exit()
  else:
    print("Invalid input")
    options_choice()

def options_menu():
    os.system('clear')
    print("#################################################")
    print("                Welcome to Mikado                ")
    print("#################################################")
    print("                     ·Play·                      ")
    print("                     ·Help·                      ")
    print("                     ·Quit·                      ")
    options()
game_over = False
solved_areas = {
       'floor1': {'a1': True, 'a2': True, 'a3': True, 'a4': True, 'a5': True, 'a7': False,
                'b1': True, 'b2': True, 'b5': True, 'b7': True,
                'c2': True, 'c3': True, 'c7': True,
                'd3': True, 'd4': True, 'd5': True, 'd6': True, 'd7': True,
                'e6': True, 'e7': True,
                'f1': True, 'f2': True, 'f3': True, 'f4': True, 'f5': True, 'f6': True, 'f7': True,
                'g6': True, 'g7': True,
                'h1': True, 'h2': True, 'h3': True, 'h4': True, 'h5': True, 'h6': True, 'h7': True,
                },
        'floor2': {'a1': False, 'a2': True, 'a4': True, 'a5': True, 'a6': True, 'a7': True,
                'b1': True, 'b2': True, 'b3': True, 'b4': True, 'b5': True, 'b6': True, 'b7': True,
                'c1': True, 'c3': True, 'c7': True,
                'd1': True, 'd3': True, 'd5': False, 'd6': True, 'd7': True,
                'e1': True, 'e2': True, 'e3': True, 'e5': True, 'e6': True, 'e7': True,
                'f1': True, 'f2': True, 'f3': True,'f5': True, 'f6': True, 'f7': True,
                'g1': True, 'g2': True, 'g3': False,'g5': True,
                },
        'floor3': {'a1': True, 'a2': True, 'a3': False, 'a6': False, 'a7': True,
                'b1': True, 'b2': True, 'b3': True, 'b6': True, 'b7': True,
                'c1': True, 'c2': True, 'c7': True,
                'd1': True, 'd2': True, 'd3': True, 'd4': True, 'd7': True,
                'e1': True, 'e2': True, 'e7': True,
                'f1': True, 'f2': True, 'f4': True, 'f6': True, 'f7': True,
                'g1': True, 'g2': True, 'g3': True, 'g4': True, 'g5': True, 'g6': True, 'g7': True,
                },
        'floor4': {'a1': False, 'a2': True, 'a3': True, 'a4': True, 'a5': True, 'a6': True, 'a7': False,
                'b1': True, 'b2': True, 'b3': True, 'b4': True, 'b5': True, 'b6': True, 'b7': True,
                'c1': True, 'c2': True, 'c4': True, 'c6': True, 'c7': True,
                'd1': True, 'd2': True, 'd3': True, 'd4': True, 'd5': True, 'd6': True, 'd7': True,
                'e1': True, 'e2': True, 'e4': True, 'e6': True, 'e7': True,
                'f1': True, 'f2': True, 'f3': True, 'f4': True, 'f5': True, 'f6': True, 'f7': True,
                'g1': False, 'g2': True, 'g3': True, 'g4': True, 'g5': True, 'g6': True, 'g7': False,
                },
        'room_to_easter_egg': {'a1': False, 'a2': True, 'a3': False,
                            'b1': True, 'b2': True, 'b3': True,
                            'c2': True,
                            },
        'floor5': {'a1': True, 'a2': True, 'a3': True, 'a4': True, 'a5': True, 'a6': True, 'a7': True,
                'b1': True, 'b2': True, 'b3': True, 'b4': True, 'b5': True, 'b6': True, 'b7': True,
                'c1': True, 'c2': True, 'c3': True, 'c4': True, 'c5': True, 'c6': True, 'c7': True,
                'd1': True, 'd2': True, 'd3': True, 'd4': True, 'd5': True, 'd6': True, 'd7': True,
                'e1': True, 'e2': True, 'e3': True, 'e4': True, 'e5': True, 'e6': True, 'e7': True,
                'f1': True, 'f2': True, 'f3': True, 'f4': True, 'f5': True, 'f6': True, 'f7': True,
                'g1': True, 'g2': True, 'g3': True, 'g4': True, 'g5': True, 'g6': True, 'g7': True,
                }
       }
area_map = {
     'floor1' :{
         'a1':{
         'up': '',
         'down': 'a2',
         'left': '',
         'right':  'b1',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a2':{
         'up': 'a1',
         'down': 'a3',
         'left': '' ,
         'right': 'b2',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a3':{
         'up': 'a2',
         'down': 'a4',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a4':{
         'up': 'a3',
         'down': 'a5',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a5':{
         'up': 'a4',
         'down': '',
         'left': '',
         'right': 'b5',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a7':{
         'up': '',
         'down': '',
         'left': '',
         'right': 'b7',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'b1':{
         'up': '',
         'down': 'b2',
         'left': 'a1',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'b2':{
         'up': 'b1',
         'down': '',
         'left': 'a2',
         'right': 'c2',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'b5':{
         'up': '',
         'down': '',
         'left': 'a5',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'b7':{
         'up': '',
         'down': '',
         'left': 'a7',
         'right': 'c7',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'c2':{
         'up': '',
         'down': 'c3',
         'left': 'b2',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'c3':{
         'up': 'c2',
         'down': '',
         'left': '',
         'right': 'd3',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'c7':{
         'up': '',
         'down': '',
         'left': 'b7',
         'right': 'd7',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'd3':{
         'up': '',
         'down': 'd4',
         'left': 'c3',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'd4':{
         'up': 'd3',
         'down': 'd5',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'd5':{
         'up': 'd4',
         'down': 'd6',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'd6':{
         'up': 'd5',
         'down': 'd7',
         'left': '',
         'right': 'e6',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'd7':{
         'up':  'd6',
         'down': '',
         'left': 'c7',
         'right': 'e7',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'e6':{
         'up': '',
         'down': 'e7',
         'left': 'd6',
         'right': 'f6',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'e7':{
         'up': 'e6',
         'down': '',
         'left': 'd7',
         'right': 'f7',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'f1':{
         'up': 'floor2[a2]',
         'down': 'f2',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'f2':{
         'up': 'f1',
         'down': 'f3',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'f3':{
         'up': 'f2',
         'down': 'f4',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'f4':{
         'up': 'f3',
         'down': 'f5',
         'left':  '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'f5':{
         'up': 'f4',
         'down': 'f6',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'f6':{
         'up': 'f5',
         'down': 'f7',
         'left': 'e6',
         'right': 'g6',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'f7':{
         'up': 'f6',
         'down': '',
         'left': 'e7',
         'right': 'g7',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'g6':{
         'up': '',
         'down': 'g7',
         'left': 'f6',
         'right': 'h6',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'g7':{
         'up': 'g6',
         'down': '',
         'left': 'f7',
         'right': 'h7',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'h1':{
         'up': '',
         'down': 'h2',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'h2':{
         'up': 'h1',
         'down': 'h2',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'h3':{
         'up': 'h2,',
         'down': 'h3',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'h4':{
         'up': 'h3',
         'down': 'h5',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'h5':{
         'up': 'h4',
         'down': 'h6',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'h6':{
         'up': 'h5',
         'down': 'h7',
         'left': 'g6',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'h7':{
         'up': 'h6',
         'down': '',
         'left': 'g7',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         }
     },
     'floor2' :{
         'a1':{
         'up': '',
         'down': 'a2',
         'left': '',
         'right':  'b1',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a2':{
         'up': 'a1',
         'down': '',
         'left': '' ,
         'right': 'b2',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a4':{
         'up': '',
         'down': 'a5',
         'left': '',
         'right': 'b4',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a5':{
         'up': 'a4',
         'down': 'a6',
         'left': '',
         'right': '',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a6':{
         'up': 'a5',
         'down': 'a7',
         'left': '',
         'right': 'b6',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a7':{
         'up': 'a6',
         'down': '',
         'left': '',
         'right': 'b7',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'b1':{
         'up': '',
         'down': 'b2',
         'left': 'a1',
         'right': 'c1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b2':{
         'up': 'b1',
         'down': '',
         'left': 'a2',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b4':{
         'up': '',
         'down': '',
         'left': 'a4',
         'right': 'c4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b6':{
         'up': '',
         'down': 'b7',
         'left': 'a6',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b7':{
         'up': 'b6',
         'down': '',
         'left': 'a7',
         'right': 'c7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c1':{
         'up': '',
         'down': '',
         'left': 'b1',
         'right': 'd1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c3':{
         'up': '',
         'down': 'c4',
         'left': '',
         'right': 'd3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c4':{
         'up': 'c3',
         'down': '',
         'left': 'b4',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c7':{
         'up': '',
         'down': '',
         'left': 'b7',
         'right': 'd7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd1':{
         'up': '',
         'down': '',
         'left': 'c1',
         'right': 'e1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd3':{
         'up': '',
         'down': '',
         'left': 'c3',
         'right': 'e3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd5':{
         'up': '',
         'down': 'd6',
         'left': '',
         'right': 'e5',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd6':{
         'up': 'd5',
         'down': 'd7',
         'left': '',
         'right': 'e6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd7':{
         'up':  'd6',
         'down': '',
         'left': 'c7',
         'right': 'e7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e1':{
         'up': '',
         'down': 'e2',
         'left': 'd1',
         'right': 'f1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e2':{
         'up': 'e1',
         'down': 'e3',
         'left': '',
         'right': 'f2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e3':{
         'up': 'e2',
         'down': '',
         'left': 'd3',
         'right': 'f3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e5':{
         'up': '',
         'down': 'e6',
         'left': 'd5',
         'right': 'f5',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e6':{
         'up': 'e5',
         'down': 'e7',
         'left': 'd6',
         'right': 'f6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e7':{
         'up': 'e6',
         'down': '',
         'left': 'd7',
         'right': 'f7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f1':{
         'up': '',
         'down': 'f2',
         'left': 'e1',
         'right': 'g1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f2':{
         'up': 'f1',
         'down': 'f3',
         'left': 'e2',
         'right': 'g2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f3':{
         'up': 'f2',
         'down': '',
         'left': 'e3',
         'right': 'g3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f5':{
         'up': '',
         'down': 'f6',
         'left': 'e5',
         'right': 'g5',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f6':{
         'up': 'f5',
         'down': 'f7',
         'left': 'e6',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f7':{
         'up': 'f6',
         'down': '',
         'left': 'e7',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g1':{
         'up': '',
         'down': 'g2',
         'left': 'f1',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g2':{
         'up': 'g1',
         'down': 'g3',
         'left': 'f2',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g3':{
         'up': 'g2',
         'down': '',
         'left': 'f3',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g5':{
         'up': '',
         'down': '',
         'left': 'f5',
         'right': 'floor3[d4]',
         'examine': '',
         'description':'',
         'solved': False,
         }
     },
     'floor3' :{
         'a1':{
         'up': '',
         'down': 'a2',
         'left': '',
         'right':  'b1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a2':{
         'up': 'a1',
         'down': 'a3',
         'left': '' ,
         'right': 'b2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a3':{
         'up': 'a2',
         'down': '',
         'left': '',
         'right': 'b3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a6':{
         'up': 'a',
         'down': 'a7',
         'left': '',
         'right': 'b6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a7':{
         'up': 'a6',
         'down': '',
         'left': '',
         'right': 'b7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b1':{
         'up': '',
         'down': 'b2',
         'left': 'a1',
         'right': 'c1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b2':{
         'up': 'b1',
         'down': 'b3',
         'left': 'a2',
         'right': 'c2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b3':{
         'up': 'b2',
         'down': '',
         'left': 'a3',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b6':{
         'up': '',
         'down': 'a6',
         'left': 'a6',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b7':{
         'up': 'b6',
         'down': '',
         'left': 'a7',
         'right': 'c7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c1':{
         'up': '',
         'down': 'c2',
         'left': 'b1',
         'right': 'd1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c2':{
         'up': 'c1',
         'down': '',
         'left': 'b2',
         'right': 'd3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c7':{
         'up': '',
         'down': '',
         'left': 'b7',
         'right': 'd7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd1':{
         'up': '',
         'down': 'd2',
         'left': 'c1',
         'right': 'e1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd2':{
         'up': 'd1',
         'down': 'd3',
         'left': 'c2',
         'right': 'e2',
         'examine': '',
         'description':'',
         'solved': False,
         },

         'd3':{
         'up': 'd2',
         'down': 'd4',
         'left': '',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd4':{
         'up': 'd3',
         'down': '',
         'left': '',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd7':{
         'up':  '',
         'down': 'floor4[d4]',
         'left': 'c7',
         'right': 'e7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e1':{
         'up': '',
         'down': 'e2',
         'left': 'd1',
         'right': 'f1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e2':{
         'up': 'e1',
         'down': '',
         'left': 'd2',
         'right': 'f2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e7':{
         'up': '',
         'down': '',
         'left': 'd7',
         'right': 'f7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f1':{
         'up': '',
         'down': 'f2',
         'left': 'e1',
         'right': 'g1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f2':{
         'up': 'f1',
         'down': '',
         'left': 'e2',
         'right': 'g2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f4':{
         'up': '',
         'down': '',
         'left': '',
         'right': 'g4',
         'examine': '',
         'description': '',
         },
         'f6':{
         'up': '',
         'down': 'f7',
         'left': '',
         'right': 'g6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f7':{
         'up': 'f6',
         'down': '',
         'left': 'e7',
         'right': 'g7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g1':{
         'up': '',
         'down': 'g2',
         'left': 'f1',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g2':{
         'up': 'g1',
         'down': 'g3',
         'left': 'f2',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g3':{
         'up': 'g2',
         'down': 'g4',
         'left': '',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g4':{
         'up': 'g3',
         'down': 'g5',
         'left': 'f4',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g5':{
         'up': 'g4',
         'down': 'g6',
         'left': '',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g6':{
         'up': 'g5',
         'down': 'g7',
         'left': 'f6',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g7':{
         'up': 'g6',
         'down': '',
         'left': 'f7',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         }
     },
     'floor4':{
         'a1':{
         'up': '',
         'down': 'a2',
         'left': '',
         'right':  'b1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a2':{
         'up': 'a1',
         'down': 'a3',
         'left': '' ,
         'right': 'b2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a3':{
         'up': 'a2',
         'down': 'a4',
         'left': '',
         'right': 'b3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a4':{
         'up': 'a3',
         'down': 'a5',
         'left': 'room_to_easter_egg[c2]',
         'right': 'b4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a5':{
         'up': 'a4',
         'down': 'a6',
         'left': '',
         'right': 'b5',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a6':{
         'up': 'a5',
         'down': 'a7',
         'left': '',
         'right': 'b6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a7':{
         'up': 'a6',
         'down': '',
         'left': '',
         'right': 'b7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b1':{
         'up': '',
         'down': 'b2',
         'left': 'a1',
         'right': 'c1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b2':{
         'up': 'b1',
         'down': 'b3',
         'left': 'a2',
         'right': 'c2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b3':{
         'up': 'b2',
         'down': 'b4',
         'left': 'a3',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b4':{
         'up': 'b3',
         'down': 'b5',
         'left': 'a4',
         'right': 'c4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b5':{
         'up': 'b4',
         'down': 'b6',
         'left': 'a5',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b6':{
         'up': 'b5',
         'down': 'b7',
         'left': 'a6',
         'right': 'c6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b7':{
         'up': 'b6',
         'down': '',
         'left': 'a7',
         'right': 'c7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c1':{
         'up': '',
         'down': 'c2',
         'left': 'b1',
         'right': 'd1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c2':{
         'up': 'c1',
         'down': '',
         'left': 'b2',
         'right': 'd2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c4':{
         'up': '',
         'down': '',
         'left': 'b4',
         'right': 'd4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c6':{
         'up': '',
         'down': 'c7',
         'left': 'b6',
         'right': 'd6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c7':{
         'up': 'c6',
         'down': '',
         'left': 'b7',
         'right': 'd7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd1':{
         'up': '',
         'down': 'd2',
         'left': 'c1',
         'right': 'e1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd2':{
         'up': 'd1',
         'down': 'd3',
         'left': 'c2',
         'right': 'e2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd3':{
         'up': 'd2',
         'down': 'd4',
         'left': '',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd4':{
         'up': 'd3',
         'down': 'd5',
         'left': 'c4',
         'right': 'e4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd5':{
         'up': 'd4',
         'down': 'd6',
         'left': '',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd6':{
         'up': 'd5',
         'down': 'd7',
         'left': 'c6',
         'right': 'e6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd7':{
         'up':  'd6',
         'down': '',
         'left': 'c7',
         'right': 'e7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e1':{
         'up': '',
         'down': 'e2',
         'left': 'd1',
         'right': 'f1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e2':{
         'up': 'e1',
         'down': '',
         'left': 'd2',
         'right': 'f2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e4':{
         'up': '',
         'down': '',
         'left': 'd4',
         'right': 'f4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e6':{
         'up': '',
         'down': 'e7',
         'left': 'd6',
         'right': 'f6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e7':{
         'up': 'e6',
         'down': '',
         'left': 'd7',
         'right': 'g7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f1':{
         'up': '',
         'down': 'f2',
         'left': 'e1',
         'right': 'g1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f2':{
         'up': 'f1',
         'down': 'f3',
         'left': 'e2',
         'right': 'g2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f3':{
         'up': 'f2',
         'down': 'f4',
         'left': '',
         'right': 'g3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f4':{
         'up': 'f3',
         'down': 'f5',
         'left':  'e4',
         'right': 'g4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f5':{
         'up': 'f4',
         'down': 'f6',
         'left': 'the_end',
         'right': 'g5',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f6':{
         'up': 'f5',
         'down': 'f7',
         'left': 'e6',
         'right': 'g6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f7':{
         'up': 'f6',
         'down': '',
         'left': 'e7',
         'right': 'g7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g1':{
         'up': '',
         'down': 'g2',
         'left': 'f1',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g2':{
         'up': 'g1',
         'down': 'g3',
         'left': 'f2',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g3':{
         'up': 'g2',
         'down': 'g4',
         'left': 'f3',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g4':{
         'up': 'g3',
         'down': 'g5',
         'left': 'f5',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g5':{
         'up': 'g4',
         'down': 'g6',
         'left': 'f5',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g6':{
         'up': 'g5',
         'down': 'g7',
         'left': 'f7',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g7':{
         'up': 'g6',
         'down': '',
         'left': 'f7',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         }
      },
     'room_to_easter_egg':{
         'a1':{
         'up': '',
         'down': 'a2',
         'left': '',
         'right':  'b1',
         'examine': '',
         'description': '',
         'solved': False,
         },
         'a2':{
         'up': 'a1',
         'down': 'a3',
         'left': 'floor5[a1]' ,
         'right': 'b2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a3':{
         'up': 'a2',
         'down': '',
         'left': '' ,
         'right': 'b3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b1':{
         'up': '',
         'down': 'b2',
         'left': 'a1' ,
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b2':{
         'up': 'b1',
         'down': 'b3',
         'left': 'a2' ,
         'right': 'c2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b3':{
         'up': 'b2',
         'down': '',
         'left': 'a3' ,
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c2':{
         'up': '',
         'down': '',
         'left': 'b2' ,
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
     },
     'floor5':{
         'a1':{
         'up': '',
         'down': 'a2',
         'left': '',
         'right':  'b1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a2':{
         'up': 'a1',
         'down': 'a3',
         'left': '' ,
         'right': 'b2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a3':{
         'up': 'a2',
         'down': 'a4',
         'left': '',
         'right': 'b3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a4':{
         'up': 'a3',
         'down': 'a5',
         'left': 'room_to_easter_egg[c2]',
         'right': 'b4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a5':{
         'up': 'a4',
         'down': 'a6',
         'left': '',
         'right': 'b5',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a6':{
         'up': 'a5',
         'down': 'a7',
         'left': '',
         'right': 'b6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'a7':{
         'up': 'a6',
         'down': '',
         'left': '',
         'right': 'b7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b1':{
         'up': '',
         'down': 'b2',
         'left': 'a1',
         'right': 'c1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b2':{
         'up': 'b1',
         'down': 'b3',
         'left': 'a2',
         'right': 'c2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b3':{
         'up': 'b2',
         'down': 'b4',
         'left': 'a3',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b4':{
         'up': 'b3',
         'down': 'b5',
         'left': 'a4',
         'right': 'c4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b5':{
         'up': 'b4',
         'down': 'b6',
         'left': 'a5',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b6':{
         'up': 'b5',
         'down': 'b7',
         'left': 'a6',
         'right': 'c6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'b7':{
         'up': 'b6',
         'down': '',
         'left': 'a7',
         'right': 'c7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c1':{
         'up': '',
         'down': 'c2',
         'left': 'b1',
         'right': 'd1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c2':{
         'up': 'c1',
         'down': '',
         'left': 'b2',
         'right': 'd2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c4':{
         'up': '',
         'down': '',
         'left': 'b4',
         'right': 'd4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c6':{
         'up': '',
         'down': 'c7',
         'left': 'b6',
         'right': 'd6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'c7':{
         'up': 'c6',
         'down': '',
         'left': 'b7',
         'right': 'd7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd1':{
         'up': '',
         'down': 'd2',
         'left': 'c1',
         'right': 'e1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd2':{
         'up': 'd1',
         'down': 'd3',
         'left': 'c2',
         'right': 'e2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd3':{
         'up': 'd2',
         'down': 'd4',
         'left': '',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd4':{
         'up': 'd3',
         'down': 'd5',
         'left': 'c4',
         'right': 'e4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd5':{
         'up': 'd4',
         'down': 'd6',
         'left': '',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd6':{
         'up': 'd5',
         'down': 'd7',
         'left': 'c6',
         'right': 'e6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'd7':{
         'up':  'd6',
         'down': '',
         'left': 'c7',
         'right': 'e7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e1':{
         'up': '',
         'down': 'e2',
         'left': 'd1',
         'right': 'f1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e2':{
         'up': 'e1',
         'down': '',
         'left': 'd2',
         'right': 'f2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e4':{
         'up': '',
         'down': '',
         'left': 'd4',
         'right': 'f4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e6':{
         'up': '',
         'down': 'e7',
         'left': 'd6',
         'right': 'f6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'e7':{
         'up': 'e6',
         'down': '',
         'left': 'd7',
         'right': 'g7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f1':{
         'up': '',
         'down': 'f2',
         'left': 'e1',
         'right': 'g1',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f2':{
         'up': 'f1',
         'down': 'f3',
         'left': 'e2',
         'right': 'g2',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f3':{
         'up': 'f2',
         'down': 'f4',
         'left': '',
         'right': 'g3',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f4':{
         'up': 'f3',
         'down': 'f5',
         'left':  'e4',
         'right': 'g4',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f5':{
         'up': 'f4',
         'down': 'f6',
         'left': 'the_end',
         'right': 'g5',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f6':{
         'up': 'f5',
         'down': 'f7',
         'left': 'e6',
         'right': 'g6',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'f7':{
         'up': 'f6',
         'down': '',
         'left': 'e7',
         'right': 'g7',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g1':{
         'up': '',
         'down': 'g2',
         'left': 'f1',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g2':{
         'up': 'g1',
         'down': 'g3',
         'left': 'f2',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g3':{
         'up': 'g2',
         'down': 'g4',
         'left': 'f3',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g4':{
         'up': 'g3',
         'down': 'g5',
         'left': 'f5',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g5':{
         'up': 'g4',
         'down': 'g6',
         'left': 'f5',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g6':{
         'up': 'g5',
         'down': 'g7',
         'left': 'f7',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         },
         'g7':{
         'up': 'g6',
         'down': '',
         'left': 'f7',
         'right': '',
         'examine': '',
         'description':'',
         'solved': False,
         }
     }
 }
class player():
    def __init__(self):
        self.name = ''
        self.hp = 100
        self.status = []
        self.location = area_map['floor1']['b5']
myplayer = player()
def actions():
    print('-------------------------------------')
    print('What would you like to do?')
    print('-------------------------------------')
    action = input('>').strip()
    if action == 'quit':
        os.system('clear')
    elif action == 'move' or action == 'go' or action == 'travel' or action == 'walk':
        players_movement(action)
    elif action == 'interact' or action == 'examine' or action == 'inspect' or action  == 'look':
        player.examine(action)
    elif action == 'options':
            print('-------------------------------------')
            possibly_lose_their_data_question = ('Are you sure?')
            possibly_lose_their_data_statement = ('This action will delete your data and you will have to start again...','\n')
            for character in possibly_lose_their_data_question:
                sys.stdout.write(character)
                sys.stdout.flush()
                time.sleep(0.0275)
            for character in possibly_lose_their_data_statement:
                sys.stdout.write(character)
                sys.stdout.flush()
                time.sleep(0.0275)
            print('-------------------------------------')
            possibly_lose_their_data_question_answer = input('>')
            if possibly_lose_their_data_question_answer == 'yes' or possibly_lose_their_data_question_answer == 'yh' or possibly_lose_their_data_question_answer == 'y':
                options_menu()
            else:
                unexacutable_action = ("I can't do that...")
                for character in unexacutable_action:
                    sys.stdout.write(character)
                    sys.stdout.flush()
                    time.sleep(0.025)
                actions()
def players_movement(myaction):
    question = 'where would you like to move?'
    print(question)
    destination = input('>')
    print('-------------------------------------')
    if destination == 'up' or destination == 'north':
        current_destination = myplayer.location['up']
        movement_controller(current_destination)
    elif destination == 'down' or destination == 'south':
        current_destination = myplayer.location['down']
        movement_controller(current_destination)
    elif destination == 'left' or destination == 'west':
        current_destination = myplayer.location['left']
        movement_controller(current_destination)
    elif destination == 'right' or destination == 'east':
        current_destination = myplayer.location['right'][name]
        movement_controller(current_destination)
def movement_controller(current_destination):
    players_current_location = ("\n" + 'I am now in ' + current_destination + '...','\n')
    for character in players_current_location:
        sys.stdout.write(character)
        sys.stdout.flush()
        time.sleep(0.039)
def player_examine(action):
    if area_map[myplayer.location][solved] == True:
        print("dsc")
    else:
        chess_lock
def primary_game():
    while game_over == False:
        actions()
def game_structure():
    os.system('clear')
    primary_game()
# def introduction():
#     before_you_enter = ('')
# introduction()
game_structure
