import os

def help_menu():
    print('hi')
def start_game():
    print('hello')
def options():
  options_choice = input(">").lower().strip()
  if options_choice  == "play":
    start_game()
  elif options_choice== "help":
    help_menu()
  elif options_choice == "quit":
    os.system("cls")
  else:
    print("Invalid input")
    options_choice()

def options_menu():
  print("##########################")
  print("   Welcome to Mikado      ")
  print("##########################")
  print("          ·Play·          ")
  print("          ·Help·          ")
  print("          ·Quit·          ")
  options()
options_menu()
class player():
    def within(self):
        self.name = ''
        self.hp = 100
        self.status = []
    mycharacter = player()
def map():
    area_map = {
        floor1 :{
            a1:{
            up: '',
            down: 'a2',
            left: '',
            right:  'b1',
            examine: '',
            description: '',
            },
            a2:{
            up: 'a1',
            down: 'a3',
            left: '' ,
            right: 'b2',
            examine: '',
            description: '',
            },
            a3:{
            up: 'a2',
            down: 'a4',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            a4:{
            up: 'a3',
            down: 'a5',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            a5:{
            up: 'a4',
            down: '',
            left: '',
            right: 'b5',
            examine: '',
            description: '',
            },
            a7:{
            up: '',
            down: '',
            left: '',
            right: 'b7',
            examine: '',
            description: '',
            },
            b1:{
            up: '',
            down: 'b2',
            left: 'a1',
            right: '',
            examine: '',
            description: '',
            },
            b2:{
            up: 'b1',
            down: '',
            left: 'a2',
            right: 'c2',
            examine: '',
            description: '',
            },
            b5:{
            up: '',
            down: '',
            left: 'a5',
            right: '',
            examine: '',
            description: '',
            },
            b7:{
            up: '',
            down: '',
            left: 'a7',
            right: 'c7',
            examine: '',
            description: '',
            },
            c2:{
            up: '',
            down: 'c3',
            left: 'b2',
            right: '',
            examine: '',
            description: '',
            },
            c3:{
            up: 'c2',
            down: '',
            left: '',
            right: 'd3',
            examine: '',
            description: '',
            },
            c7:{
            up: '',
            down: '',
            left: 'b7',
            right: 'd7',
            examine: '',
            description: '',
            },
            d3:{
            up: '',
            down: 'd4',
            left: 'c3',
            right: '',
            examine: '',
            description: '',
            },
            d4:{
            up: 'd3',
            down: 'd5',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            d5:{
            up: 'd4',
            down: 'd6',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            d6:{
            up: 'd5',
            down: 'd7',
            left: '',
            right: 'e6',
            examine: '',
            description: '',
            },
            d7:{
            up:  'd6',
            down: '',
            left: 'c7',
            right: 'e7',
            examine: '',
            description: '',
            },
            e6:{
            up: '',
            down: 'e7',
            left: 'd6',
            right: 'f6',
            examine: '',
            description: '',
            },
            e7:{
            up: 'e6',
            down: '',
            left: 'd7',
            right: 'f7',
            examine: '',
            description: '',
            },
            f1:{
            up: 'floor2[a2]',
            down: 'f2',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            f2:{
            up: 'f1',
            down: 'f3',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            f3:{
            up: 'f2',
            down: 'f4',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            f4:{
            up: 'f3',
            down: 'f5',
            left:  '',
            right: '',
            examine: '',
            description: '',
            },
            f5:{
            up: 'f4',
            down: 'f6',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            f6:{
            up: 'f5',
            down: 'f7',
            left: 'e6',
            right: 'g6',
            examine: '',
            description: '',
            },
            f7:{
            up: 'f6',
            down: '',
            left: 'e7',
            right: 'g7',
            examine: '',
            description: '',
            },
            g6:{
            up: '',
            down: 'g7',
            left: 'f6',
            right: 'h6',
            examine: '',
            description: '',
            },
            g7:{
            up: 'g6',
            down: '',
            left: 'f7',
            right: 'h7',
            examine: '',
            description: '',
            },
            h1:{
            up: '',
            down: 'h2',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            h2:{
            up: 'h1',
            down: 'h2',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            h3:{
            up: 'h2,',
            down: 'h3',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            h4:{
            up: 'h3',
            down: 'h5',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            h5:{
            up: 'h4',
            down: 'h6',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            h6:{
            up: 'h5',
            down: 'h7',
            left: 'g6',
            right: '',
            examine: '',
            description: '',
            },
            h7:{
            up: 'h6',
            down: '',
            left: 'g7',
            right: '',
            examine: '',
            description: '',
            }
        },
        floor2 :{
            a1:{
            up: '',
            down: 'a2',
            left: '',
            right:  'b1',
            examine: '',
            description: '',
            },
            a2:{
            up: 'a1',
            down: '',
            left: '' ,
            right: 'b2',
            examine: '',
            description: '',
            },
            a4:{
            up: '',
            down: 'a5',
            left: '',
            right: 'b4',
            examine: '',
            description: '',
            },
            a5:{
            up: 'a4',
            down: 'a6',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            a6:{
            up: 'a5',
            down: 'a7',
            left: '',
            right: 'b6',
            examine: '',
            description: '',
            },
            a7:{
            up: 'a6',
            down: '',
            left: '',
            right: 'b7',
            examine: '',
            description: '',
            },
            b1:{
            up: '',
            down: 'b2',
            left: 'a1',
            right: 'c1',
            examine: '',
            description: '',
            },
            b2:{
            up: 'b1',
            down: '',
            left: 'a2',
            right: '',
            examine: '',
            description: '',
            },
            b4:{
            up: '',
            down: '',
            left: 'a4',
            right: 'c4',
            examine: '',
            description: '',
            },
            b6:{
            up: '',
            down: 'b7',
            left: 'a6',
            right: '',
            examine: '',
            description: '',
            },
            b7:{
            up: 'b6',
            down: '',
            left: 'a7',
            right: 'c7',
            examine: '',
            description: '',
            },
            c1:{
            up: '',
            down: '',
            left: 'b1',
            right: 'd1',
            examine: '',
            description: '',
            },
            c3:{
            up: '',
            down: 'c4',
            left: '',
            right: 'd3',
            examine: '',
            description: '',
            },
            c4:{
            up: 'c3',
            down: '',
            left: 'b4',
            right: '',
            examine: '',
            description: '',
            },
            c7:{
            up: '',
            down: '',
            left: 'b7',
            right: 'd7',
            examine: '',
            description: '',
            },
            d1:{
            up: '',
            down: '',
            left: 'c1',
            right: 'e1',
            examine: '',
            description: '',
            },
            d3:{
            up: '',
            down: '',
            left: 'c3',
            right: 'e3',
            examine: '',
            description: '',
            },
            d5:{
            up: '',
            down: 'd6',
            left: '',
            right: 'e5',
            examine: '',
            description: '',
            },
            d6:{
            up: 'd5',
            down: 'd7',
            left: '',
            right: 'e6',
            examine: '',
            description: '',
            },
            d7:{
            up:  'd6',
            down: '',
            left: 'c7',
            right: 'e7',
            examine: '',
            description: '',
            },
            e1:{
            up: '',
            down: 'e2',
            left: 'd1',
            right: 'f1',
            examine: '',
            description: '',
            },
            e2:{
            up: 'e1',
            down: 'e3',
            left: '',
            right: 'f2',
            examine: '',
            description: '',
            },
            e3:{
            up: 'e2',
            down: '',
            left: 'd3',
            right: 'f3',
            examine: '',
            description: '',
            },
            e5:{
            up: '',
            down: 'e6',
            left: 'd5',
            right: 'f5',
            examine: '',
            description: '',
            },
            e6:{
            up: 'e5',
            down: 'e7',
            left: 'd6',
            right: 'f6',
            examine: '',
            description: '',
            },
            e7:{
            up: 'e6',
            down: '',
            left: 'd7',
            right: 'f7',
            examine: '',
            description: '',
            },
            f1:{
            up: '',
            down: 'f2',
            left: 'e1',
            right: 'g1',
            examine: '',
            description: '',
            },
            f2:{
            up: 'f1',
            down: 'f3',
            left: 'e2',
            right: 'g2',
            examine: '',
            description: '',
            },
            f3:{
            up: 'f2',
            down: '',
            left: 'e3',
            right: 'g3',
            examine: '',
            description: '',
            },
            f5:{
            up: '',
            down: 'f6',
            left: 'e5',
            right: 'g5',
            examine: '',
            description: '',
            },
            f6:{
            up: 'f5',
            down: 'f7',
            left: 'e6',
            right: '',
            examine: '',
            description: '',
            },
            f7:{
            up: 'f6',
            down: '',
            left: 'e7',
            right: '',
            examine: '',
            description: '',
            },
            g1:{
            up: '',
            down: 'g2',
            left: 'f1',
            right: '',
            examine: '',
            description: '',
            },
            g2:{
            up: 'g1',
            down: 'g3',
            left: 'f2',
            right: '',
            examine: '',
            description: '',
            },
            g3:{
            up: 'g2',
            down: '',
            left: 'f3',
            right: '',
            examine: '',
            description: '',
            },
            g5:{
            up: '',
            down: '',
            left: 'f5',
            right: 'floor3[d4]',
            examine: '',
            description: '',
            }
        },
        floor3 :{
            a1:{
            up: '',
            down: 'a2',
            left: '',
            right:  'b1',
            examine: '',
            description: '',
            },
            a2:{
            up: 'a1',
            down: 'a3',
            left: '' ,
            right: 'b2',
            examine: '',
            description: '',
            },
            a3:{
            up: 'a2',
            down: '',
            left: '',
            right: 'b3',
            examine: '',
            description: '',
            },
            a6:{
            up: 'a',
            down: 'a7',
            left: '',
            right: 'b6',
            examine: '',
            description: '',
            },
            a7:{
            up: 'a6',
            down: '',
            left: '',
            right: 'b7',
            examine: '',
            description: '',
            },
            b1:{
            up: '',
            down: 'b2',
            left: 'a1',
            right: 'c1',
            examine: '',
            description: '',
            },
            b2:{
            up: 'b1',
            down: 'b3',
            left: 'a2',
            right: 'c2',
            examine: '',
            description: '',
            },
            b3:{
            up: 'b2',
            down: '',
            left: 'a3',
            right: '',
            examine: '',
            description: '',
            },
            b6:{
            up: '',
            down: 'a6',
            left: 'a6',
            right: '',
            examine: '',
            description: '',
            },
            b7:{
            up: 'b6',
            down: '',
            left: 'a7',
            right: 'c7',
            examine: '',
            description: '',
            },
            c1:{
            up: '',
            down: 'c2',
            left: 'b1',
            right: 'd1',
            examine: '',
            description: '',
            },
            c2:{
            up: 'c1',
            down: '',
            left: 'b2',
            right: 'd3',
            examine: '',
            description: '',
            },
            c7:{
            up: '',
            down: '',
            left: 'b7',
            right: 'd7',
            examine: '',
            description: '',
            },
            d1:{
            up: '',
            down: 'd2',
            left: 'c1',
            right: 'e1',
            examine: '',
            description: '',
            },
            d2:{
            up: 'd1',
            down: 'd3',
            left: 'c2',
            right: 'e2',
            examine: '',
            description: '',
            },

            d3:{
            up: 'd2',
            down: 'd4',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            d4:{
            up: 'd3',
            down: '',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            d7:{
            up:  '',
            down: 'floor4[d4]',
            left: 'c7',
            right: 'e7',
            examine: '',
            description: '',
            },
            e1:{
            up: '',
            down: 'e2',
            left: 'd1',
            right: 'f1',
            examine: '',
            description: '',
            },
            e2:{
            up: 'e1',
            down: '',
            left: 'd2',
            right: 'f2',
            examine: '',
            description: '',
            },
            e7:{
            up: '',
            down: '',
            left: 'd7',
            right: 'f7',
            examine: '',
            description: '',
            },
            f1:{
            up: '',
            down: 'f2',
            left: 'e1',
            right: 'g1',
            examine: '',
            description: '',
            },
            f2:{
            up: 'f1',
            down: '',
            left: 'e2',
            right: 'g2',
            examine: '',
            description: '',
            },
            f4:{
            up: '',
            down: '',
            left: '',
            right: 'g4',
            examine: '',
            description: '',
            },
            f6:{
            up: '',
            down: 'f7',
            left: '',
            right: 'g6',
            examine: '',
            description: '',
            },
            f7:{
            up: 'f6',
            down: '',
            left: 'e7',
            right: 'g7',
            examine: '',
            description: '',
            },
            g1:{
            up: '',
            down: 'g2',
            left: 'f1',
            right: '',
            examine: '',
            description: '',
            },
            g2:{
            up: 'g1',
            down: 'g3',
            left: 'f2',
            right: '',
            examine: '',
            description: '',
            },
            g3:{
            up: 'g2',
            down: 'g4',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            g4:{
            up: 'g3',
            down: 'g5',
            left: 'f4',
            right: '',
            examine: '',
            description: '',
            },
            g5:{
            up: 'g4',
            down: 'g6',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            g6:{
            up: 'g5',
            down: 'g7',
            left: 'f6',
            right: '',
            examine: '',
            description: '',
            },
            g7:{
            up: 'g6',
            down: '',
            left: 'f7',
            right: '',
            examine: '',
            description: '',
            }
        },
        floor4:{
            a1:{
            up: '',
            down: 'a2',
            left: '',
            right:  'b1',
            examine: '',
            description: '',
            },
            a2:{
            up: 'a1',
            down: 'a3',
            left: '' ,
            right: 'b2',
            examine: '',
            description: '',
            },
            a3:{
            up: 'a2',
            down: 'a4',
            left: '',
            right: 'b3',
            examine: '',
            description: '',
            },
            a4:{
            up: 'a3',
            down: 'a5',
            left: '',
            right: 'b4',
            examine: '',
            description: '',
            },
            a5:{
            up: 'a4',
            down: 'a6',
            left: '',
            right: 'b5',
            examine: '',
            description: '',
            },
            a6:{
            up: 'a5',
            down: 'a7',
            left: '',
            right: 'b6',
            examine: '',
            description: '',
            },
            a7:{
            up: 'a6',
            down: '',
            left: '',
            right: 'b7',
            examine: '',
            description: '',
            },
            b1:{
            up: '',
            down: 'b2',
            left: 'a1',
            right: 'c1',
            examine: '',
            description: '',
            },
            b2:{
            up: 'b1',
            down: 'b3',
            left: 'a2',
            right: 'c2',
            examine: '',
            description: '',
            },
            b3:{
            up: 'b2',
            down: 'b4',
            left: 'a3',
            right: '',
            examine: '',
            description: '',
            },
            b4:{
            up: 'b3',
            down: 'b5',
            left: 'a4',
            right: 'c4',
            examine: '',
            description: '',
            },
            b5:{
            up: 'b4',
            down: 'b6',
            left: 'a5',
            right: '',
            examine: '',
            description: '',
            },
            b6:{
            up: 'b5',
            down: 'b7',
            left: 'a6',
            right: 'c6',
            examine: '',
            description: '',
            },
            b7:{
            up: 'b6',
            down: '',
            left: 'a7',
            right: 'c7',
            examine: '',
            description: '',
            },
            c1:{
            up: '',
            down: 'c2',
            left: 'b1',
            right: 'd1',
            examine: '',
            description: '',
            },
            c2:{
            up: 'c1',
            down: '',
            left: 'b2',
            right: 'd2',
            examine: '',
            description: '',
            },
            c4:{
            up: '',
            down: '',
            left: 'b4',
            right: 'd4',
            examine: '',
            description: '',
            },
            c6:{
            up: '',
            down: 'c7',
            left: 'b6',
            right: 'd6',
            examine: '',
            description: '',
            },
            c7:{
            up: 'c6',
            down: '',
            left: 'b7',
            right: 'd7',
            examine: '',
            description: '',
            },
            d1:{
            up: '',
            down: 'd2',
            left: 'c1',
            right: 'e1',
            examine: '',
            description: '',
            },
            d2:{
            up: 'd1',
            down: 'd3',
            left: 'c2',
            right: 'e2',
            examine: '',
            description: '',
            },
            d3:{
            up: 'd2',
            down: 'd4',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            d4:{
            up: 'd3',
            down: 'd5',
            left: 'c4',
            right: 'e4',
            examine: '',
            description: '',
            },
            d5:{
            up: 'd4',
            down: 'd6',
            left: '',
            right: '',
            examine: '',
            description: '',
            },
            d6:{
            up: 'd5',
            down: 'd7',
            left: 'c6',
            right: 'e6',
            examine: '',
            description: '',
            },
            d7:{
            up:  'd6',
            down: '',
            left: 'c7',
            right: 'e7',
            examine: '',
            description: '',
            },
            e1:{
            up: '',
            down: 'e2',
            left: 'd1',
            right: 'f1',
            examine: '',
            description: '',
            },
            e2:{
            up: 'e1',
            down: '',
            left: 'd2',
            right: 'f2',
            examine: '',
            description: '',
            },
            e4:{
            up: '',
            down: '',
            left: 'd4',
            right: 'f4',
            examine: '',
            description: '',
            },
            e6:{
            up: '',
            down: 'e7',
            left: 'd6',
            right: 'f6',
            examine: '',
            description: '',
            },
            e7:{
            up: 'e6',
            down: '',
            left: 'd7',
            right: 'g7',
            examine: '',
            description: '',
            },
            f1:{
            up: '',
            down: 'f2',
            left: 'e1',
            right: 'g1',
            examine: '',
            description: '',
            },
            f2:{
            up: 'f1',
            down: 'f3',
            left: 'e2',
            right: 'g2',
            examine: '',
            description: '',
            },
            f3:{
            up: 'f2',
            down: 'f4',
            left: '',
            right: 'g3',
            examine: '',
            description: '',
            },
            f4:{
            up: 'f3',
            down: 'f5',
            left:  'e4',
            right: 'g4',
            examine: '',
            description: '',
            },
            f5:{
            up: 'f4',
            down: 'f6',
            left: 'the_end',
            right: 'g5',
            examine: '',
            description: '',
            },
            f6:{
            up: 'f5',
            down: 'f7',
            left: 'e6',
            right: 'g6',
            examine: '',
            description: '',
            },
            f7:{
            up: 'f6',
            down: '',
            left: 'e7',
            right: 'g7',
            examine: '',
            description: '',
            },
            g1:{
            up: '',
            down: 'g2',
            left: 'f1',
            right: '',
            examine: '',
            description: '',
            },
            g2:{
            up: 'g1',
            down: 'g3',
            left: 'f2',
            right: '',
            examine: '',
            description: '',
            },
            g3:{
            up: 'g2',
            down: 'g4',
            left: 'f3',
            right: '',
            examine: '',
            description: '',
            },
            g4:{
            up: 'g3',
            down: 'g5',
            left: 'f5',
            right: '',
            examine: '',
            description: '',
            },
            g5:{
            up: 'g4',
            down: 'g6',
            left: 'f5',
            right: '',
            examine: '',
            description: '',
            },
            g6:{
            up: 'g5',
            down: 'g7',
            left: 'f7',
            right: '',
            examine: '',
            description: '',
            },
            g7:{
            up: 'g6',
            down: '',
            left: 'f7',
            right: '',
            examine: '',
            description: '',
            }
        }
# ############################################################################
#         floor5 :{
#             a1:{
#             up: '',
#             down: 'a2',
#             left: '',
#             right:  'b1',
#             examine: '',
#             description: '',
#             },
#             a2:{
#             up: 'a1',
#             down: 'a3',
#             left: '' ,
#             right: 'b2',
#             examine: '',
#             description: '',
#             },
#             a3:{
#             up: 'a2',
#             down: 'a4',
#             left: '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             a4:{
#             up: 'a3',
#             down: 'a5',
#             left: '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             a5:{
#             up: 'a4',
#             down: '',
#             left: '',
#             right: 'b5',
#             examine: '',
#             description: '',
#             },
#             a7:{
#             up: '',
#             down: '',
#             left: '',
#             right: 'b7',
#             examine: '',
#             description: '',
#             },
#             b1:{
#             up: '',
#             down: 'b2',
#             left: 'a1',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             b2:{
#             up: 'b1',
#             down: '',
#             left: 'a2',
#             right: 'c2',
#             examine: '',
#             description: '',
#             },
#             b5:{
#             up: '',
#             down: '',
#             left: 'a5',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             b7:{
#             up: '',
#             down: '',
#             left: 'a7',
#             right: 'c7',
#             examine: '',
#             description: '',
#             },
#             c2:{
#             up: '',
#             down: 'c3',
#             left: 'b2',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             c3:{
#             up: 'c2',
#             down: '',
#             left: '',
#             right: 'd3',
#             examine: '',
#             description: '',
#             },
#             c7:{
#             up: '',
#             down: '',
#             left: 'b7',
#             right: 'd7',
#             examine: '',
#             description: '',
#             },
#             d3:{
#             up: '',
#             down: 'd4',
#             left: 'c3',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             d4:{
#             up: 'd3',
#             down: 'd5',
#             left: '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             d5:{
#             up: 'd4',
#             down: 'd6',
#             left: '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             d6:{
#             up: 'd5',
#             down: 'd7',
#             left: '',
#             right: 'e6',
#             examine: '',
#             description: '',
#             },
#             d7:{
#             up:  'd6',
#             down: '',
#             left: 'c7',
#             right: 'e7',
#             examine: '',
#             description: '',
#             },
#             e6:{
#             up: '',
#             down: 'e7',
#             left: 'd6',
#             right: 'f6',
#             examine: '',
#             description: '',
#             },
#             e7:{
#             up: 'e6',
#             down: '',
#             left: 'd7',
#             right: 'g7',
#             examine: '',
#             description: '',
#             },
#             f1:{
#             up: 'floor2',
#             down: 'f2',
#             left: '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             f2:{
#             up: 'f1',
#             down: 'f3',
#             left: '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             f3:{
#             up: 'f2',
#             down: 'f4',
#             left: '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             f4:{
#             up: 'f3',
#             down: 'f5',
#             left:  '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             f5:{
#             up: 'f4',
#             down: 'f6',
#             left: '',
#             right: '',
#             examine: '',
#             description: '',
#             },
#             f6:{
#             up: 'f5',
#             down: 'f7',
#             left: 'e6',
#             right: 'g7',
#             examine: '',
#             description: '',
#             },
#             f7:{
#             up: 'f6',
#             down: '',
#             left: 'e7',
#             right: 'g7',
#             examine: '',
#             description: '',
#             },
#             g6:{
#             up: '',
#             down: 'g7',
#             left: 'f6',
#             right: 'h6',
#             examine: '',
#             description: '',
#             },
#             g7:{
#             up: 'g6',
#             down: '',
#             left: 'f7',
#             right: 'h7',
#             examine: '',
#             description: '',
#             }
# ##############################################################################

    }
def print_location():
    print('\n' + ('#' * (4 + len(mycharacter.location))))
    print('#' + mycharacter.location.upper() + '#')
    print('#' + area_map[mycharacter.postion][description] + '#')
    print('\n' + ('#' * (4 + len(mycharacter.location))))

def actions():
    print('-------------------------------------')
    print('What would you like to do?')
    action = input('>')
    acceptable_actions = ['travel','move','walk','quit','interact','examine','inspect',]
def players_movement(myaction):
    question = 'where would you like to move?'
    print(question)
    destination = input('>').lower()
    if destination == ['up','north']:
        current_destination = area_map[myplayer.location][up]

    elif destination == ['down','south']:
        current_destination = area_map[myplayer.location][down]
    elif destination == ['left','west']:
        current_destination = area_map[myplayer.location][left]
    elif destination == ['right','west']:
        current_destination = area_map[myplayer.location][right]
